"""
SevaSetu — Form Generator
Generates auto-filled PDF application forms using fpdf2.
"""

from fpdf import FPDF
import os
import uuid
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "generated_forms")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class SevasetuPDF(FPDF):
    """Custom PDF class with SevaSetu branding."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(20, 60, 120)
        self.cell(0, 8, "GOVERNMENT OF INDIA", ln=True, align="C")
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 7, "Application Form", ln=True, align="C")
        self.set_draw_color(20, 60, 120)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, f"Generated by SevaSetu | {datetime.now().strftime('%d-%b-%Y %H:%M')}", align="C", ln=True)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(230, 240, 250)
        self.set_text_color(20, 60, 120)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.ln(2)

    def field_row(self, label, value):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(60, 60, 60)
        self.cell(65, 7, f"  {label}:", align="L")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 7, str(value) if value else "___________________", ln=True)

    def add_checkbox(self, label, checked=False):
        marker = "[X]" if checked else "[  ]"
        self.set_font("Helvetica", "", 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 6, f"    {marker}  {label}", ln=True)


async def generate_form(form_data: dict) -> dict:
    """
    Generate a filled PDF application form.

    Args:
        form_data: dict with applicant info, scheme details, document data

    Returns:
        dict with file path and metadata
    """
    pdf = SevasetuPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    scheme_name = form_data.get("scheme_name", "Government Welfare Scheme")
    applicant = form_data.get("applicant", {})
    documents = form_data.get("documents", {})

    # Scheme Title
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(0, 80, 40)
    pdf.cell(0, 10, scheme_name, ln=True, align="C")
    pdf.ln(3)

    # Application Reference
    app_ref = f"SEVA-{datetime.now().strftime('%Y%m%d')}-{str(uuid.uuid4())[:6].upper()}"
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Application Reference: {app_ref}", ln=True, align="C")
    pdf.ln(5)

    # Section 1: Personal Details
    pdf.section_title("1. PERSONAL DETAILS")
    pdf.field_row("Full Name", applicant.get("name"))
    pdf.field_row("Father's / Husband's Name", applicant.get("father_name"))
    pdf.field_row("Date of Birth", applicant.get("dob"))
    pdf.field_row("Gender", applicant.get("gender"))
    pdf.field_row("Age", applicant.get("age"))
    pdf.field_row("Category", applicant.get("category"))
    pdf.field_row("Mobile Number", applicant.get("phone"))
    pdf.field_row("Aadhaar Number", applicant.get("aadhaar_number"))
    pdf.ln(3)

    # Section 2: Address
    pdf.section_title("2. ADDRESS DETAILS")
    address = applicant.get("address", {})
    pdf.field_row("Address Line 1", address.get("line1"))
    pdf.field_row("Address Line 2", address.get("line2"))
    pdf.field_row("Village / Town", address.get("village") or address.get("line2"))
    pdf.field_row("District", address.get("district"))
    pdf.field_row("State", address.get("state"))
    pdf.field_row("PIN Code", address.get("pincode"))
    pdf.ln(3)

    # Section 3: Bank Details
    pdf.section_title("3. BANK ACCOUNT DETAILS")
    bank = documents.get("bank", {})
    pdf.field_row("Bank Name", bank.get("bank_name"))
    pdf.field_row("Branch", bank.get("branch"))
    pdf.field_row("Account Number", bank.get("account_number"))
    pdf.field_row("IFSC Code", bank.get("ifsc_code"))
    pdf.ln(3)

    # Section 4: Scheme-specific Info
    pdf.section_title("4. SCHEME-SPECIFIC INFORMATION")
    scheme_info = form_data.get("scheme_specific", {})
    if scheme_info:
        for key, value in scheme_info.items():
            label = key.replace("_", " ").title()
            pdf.field_row(label, value)
    else:
        pdf.field_row("Occupation", applicant.get("occupation"))
        pdf.field_row("Annual Income (₹)", applicant.get("income"))
        pdf.field_row("Land Holding (hectares)", applicant.get("land_holding"))
    pdf.ln(3)

    # Section 5: Documents Attached
    pdf.section_title("5. DOCUMENTS ATTACHED")
    doc_list = form_data.get("required_documents", [
        "Aadhaar Card", "Bank Passbook", "Income Certificate"
    ])
    for doc in doc_list:
        pdf.add_checkbox(doc, checked=True)
    pdf.ln(5)

    # Declaration
    pdf.section_title("6. DECLARATION")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)
    declaration = (
        "I hereby declare that the information provided above is true and correct to the best of my knowledge. "
        "I understand that any false information may lead to rejection of this application and/or legal action. "
        "I authorize the concerned authorities to verify the details provided."
    )
    pdf.multi_cell(0, 5, declaration)
    pdf.ln(8)

    # Signature
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(95, 6, "Date: ____________________", align="L")
    pdf.cell(95, 6, "Signature: ____________________", align="R", ln=True)
    pdf.ln(3)
    pdf.cell(95, 6, f"Place: {address.get('district', '____________________')}", align="L")
    pdf.cell(95, 6, f"Name: {applicant.get('name', '____________________')}", align="R", ln=True)

    # Save PDF
    file_name = f"application_{app_ref}.pdf"
    file_path = os.path.join(OUTPUT_DIR, file_name)
    pdf.output(file_path)

    return {
        "status": "success",
        "application_reference": app_ref,
        "file_name": file_name,
        "file_path": file_path,
        "message": f"Application form generated successfully. Reference: {app_ref}",
    }
