"""
SevaSetu — Grievance Letter Generator
Generates formal grievance drafts when applications are rejected.
"""

from fpdf import FPDF
import os
import uuid
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "generated_forms")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class GrievancePDF(FPDF):
    """Custom PDF for grievance letters."""

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(140, 20, 20)
        self.cell(0, 8, "GRIEVANCE APPLICATION", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Under Right to Public Services / Centralized Public Grievance Redress Mechanism", ln=True, align="C")
        self.set_draw_color(140, 20, 20)
        self.set_line_width(0.4)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 5, f"Generated by SevaSetu on {datetime.now().strftime('%d-%b-%Y')} | For official submission", align="C")


def sanitize_data(data):
    """Replace unsupported characters like ₹ for PDF generation."""
    if isinstance(data, str):
        return data.replace("₹", "Rs. ")
    elif isinstance(data, dict):
        return {k: sanitize_data(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [sanitize_data(v) for v in data]
    return data


async def generate_grievance(grievance_data: dict) -> dict:
    """
    Generate a formal grievance letter PDF.

    Args:
        grievance_data: dict with applicant_name, scheme_name, rejection_reason,
                        application_reference, details, contact info
    """
    grievance_data = sanitize_data(grievance_data)
    
    pdf = GrievancePDF()
    pdf.add_page()

    applicant = grievance_data.get("applicant_name", "Applicant Name")
    scheme = grievance_data.get("scheme_name", "Government Scheme")
    reason = grievance_data.get("rejection_reason", "Application rejected without detailed explanation")
    app_ref = grievance_data.get("application_reference", "N/A")
    details = grievance_data.get("details", "")
    address = grievance_data.get("address", "")
    phone = grievance_data.get("phone", "")

    grievance_ref = f"GRV-{datetime.now().strftime('%Y%m%d')}-{str(uuid.uuid4())[:6].upper()}"
    today = datetime.now().strftime("%d %B %Y")

    # Reference and Date
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 6, f"Grievance Reference: {grievance_ref}", ln=True)
    pdf.cell(0, 6, f"Date: {today}", ln=True)
    pdf.ln(5)

    # To Section
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "To,", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "The Grievance Redressal Officer,", ln=True)
    pdf.cell(0, 6, f"Department handling: {scheme},", ln=True)
    pdf.cell(0, 6, "Government of India", ln=True)
    pdf.ln(5)

    # Subject
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Subject: Grievance regarding rejection of application for {scheme}", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Application Reference: {app_ref}", ln=True)
    pdf.ln(5)

    # Salutation
    pdf.cell(0, 6, "Respected Sir/Madam,", ln=True)
    pdf.ln(3)

    # Body
    body_para1 = (
        f"I, {applicant}, respectfully submit this grievance regarding the rejection of my application "
        f"for the {scheme} scheme. My application (Reference: {app_ref}) was submitted with all "
        f"required documents and I believe I meet the eligibility criteria for this scheme."
    )
    pdf.multi_cell(0, 5.5, body_para1)
    pdf.ln(3)

    # Rejection Reason
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Reason for Rejection (as communicated):", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(255, 240, 240)
    pdf.multi_cell(0, 5.5, f"  {reason}", fill=True)
    pdf.ln(3)

    # Grounds for review
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Grounds for Requesting Review:", ln=True)
    pdf.set_font("Helvetica", "", 10)

    if details:
        pdf.multi_cell(0, 5.5, details)
    else:
        grounds = (
            "1. All documents submitted were valid and verified at the time of application.\n"
            "2. I meet the eligibility criteria as specified in the scheme guidelines.\n"
            "3. I request a detailed explanation for the rejection and an opportunity to resubmit "
            "any additional documents if required.\n"
            "4. I request that my application be reviewed under the provisions of the "
            "Right to Public Services Act."
        )
        pdf.multi_cell(0, 5.5, grounds)
    pdf.ln(3)

    # Request
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Prayer/Request:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    request_text = (
        "I humbly request you to kindly review my application and provide a detailed explanation "
        "for the rejection. If there are any deficiencies in my application, I request an opportunity "
        "to rectify them. I trust that the concerned authorities will ensure fair and transparent "
        "processing of my application."
    )
    pdf.multi_cell(0, 5.5, request_text)
    pdf.ln(5)

    # Documents enclosed
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Documents Enclosed:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    enclosed = [
        "Copy of original application",
        "Copy of rejection notice / communication",
        "Supporting documents (Aadhaar, Bank Passbook, etc.)",
        "Any additional proof of eligibility"
    ]
    for doc in enclosed:
        pdf.cell(0, 5.5, f"  - {doc}", ln=True)
    pdf.ln(5)

    # Closing
    pdf.cell(0, 6, "Thanking you,", ln=True)
    pdf.cell(0, 6, "Yours faithfully,", ln=True)
    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, applicant, ln=True)
    if address:
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 5, address, ln=True)
    if phone:
        pdf.cell(0, 5, f"Phone: {phone}", ln=True)

    # Save
    file_name = f"grievance_{grievance_ref}.pdf"
    file_path = os.path.join(OUTPUT_DIR, file_name)
    pdf.output(file_path)

    return {
        "status": "success",
        "grievance_reference": grievance_ref,
        "file_name": file_name,
        "file_path": file_path,
        "message": f"Grievance letter generated with reference {grievance_ref}. Print and submit to the concerned authority.",
    }
